name: Run Google Demo UI tests
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # Manually trigger the workflow
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.0-noble
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenJDK
        run: |
          apt-get update
          apt-get install -y openjdk-17-jre
          echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run Playwright UI tests
      - name: Run Google Demo UI tests
        run: npm run test:ui
        env:
          QASE_MODE: ${{ secrets.QASE_MODE }}
          QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
          QASE_PROJECT_ID: ${{ secrets.QASE_PROJECT_ID }}
        continue-on-error: true

      # Send Telegram notification
      - name: Send Telegram notification
        if: always()
        run: npm run notify
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          QASE_PROJECT_ID: ${{ secrets.QASE_PROJECT_ID }}

      # Create Allure report
      - name: Create Allure report
        run: npm run allure-report

      # Save allure report into artifacts
      - name: Save Allure report
        uses: actions/upload-artifact@v4
        with:
          name: regression-report
          path: ./allure-report

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          destination_dir: allure-report
